---
- name: reiniciar Apache
  hosts: web_servers
  become: yes
  tasks:
  - name: Asegurar que Apache está habilitado y corriendo
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
  - name: Verificar que Apache está corriendo
      ansible.builtin.service_facts:
  - name: Mostrar estado del servicio Apache
      debug:
        msg: "Estado actual de Apache: {{ ansible_facts.services httpd.state }}"
