---
- name: Reiniciar Apache
  hosts: web_servers
  become: yes
  tasks:
    - name: Asegurar que Apache está habilitado y corriendo
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
